export const movies = [
  {
    id: 8,
    title: 'Memento',
    year: '2000',
    runtime: '113',
    genres: ['Mystery', 'Thriller'],
    director: 'Christopher Nolan',
    actors: 'Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior',
    plot: "A man juggles searching for his wife's murderer and keeping his short-term memory loss from being an obstacle.",
    posterUrl:
      'https://www.moviemem.com/wp-content/uploads/2020/07/MEMENTO1SH.jpg',
  },
  {
    id: 21,
    title: 'Black Swan',
    year: '2010',
    runtime: '108',
    genres: ['Drama', 'Thriller'],
    director: 'Darren Aronofsky',
    actors: 'Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey',
    plot: 'A committed dancer wins the lead role in a production of Tchaikovsky\'s "Swan Lake" only to find herself struggling to maintain her sanity.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg',
  },
  {
    id: 49,
    title: 'The Truman Show',
    year: '1998',
    runtime: '103',
    genres: ['Comedy', 'Drama', 'Sci-Fi'],
    director: 'Peter Weir',
    actors: 'Jim Carrey, Laura Linney, Noah Emmerich, Natascha McElhone',
    plot: 'An insurance salesman/adjuster discovers his entire life is actually a television show.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg',
  },
  {
    id: 53,
    title: 'Vicky Cristina Barcelona',
    year: '2008',
    runtime: '96',
    genres: ['Drama', 'Romance'],
    director: 'Woody Allen',
    actors:
      'Rebecca Hall, Scarlett Johansson, Christopher Evan Welch, Chris Messina',
    plot: 'Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2NDQ4MTg2MV5BMl5BanBnXkFtZTcwNDUzNjU3MQ@@._V1_SX300.jpg',
  },
  {
    id: 55,
    title: 'Lost in Translation',
    year: '2003',
    runtime: '101',
    genres: ['Drama'],
    director: 'Sofia Coppola',
    actors:
      'Scarlett Johansson, Bill Murray, Akiko Takeshita, Kazuyoshi Minamimagoe',
    plot: 'A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTI2NDI5ODk4N15BMl5BanBnXkFtZTYwMTI3NTE3._V1_SX300.jpg',
  },
  {
    id: 65,
    title: 'The Social Network',
    year: '2010',
    runtime: '120',
    genres: ['Biography', 'Drama'],
    director: 'David Fincher',
    actors: 'Jesse Eisenberg, Rooney Mara, Bryan Barter, Dustin Fitzsimons',
    plot: 'Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the co-founder who was later squeezed out of the business.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2ODk0NDAwMF5BMl5BanBnXkFtZTcwNTM1MDc2Mw@@._V1_SX300.jpg',
  },
  {
    id: 78,
    title: 'Oldboy',
    year: '2003',
    runtime: '120',
    genres: ['Drama', 'Mystery', 'Thriller'],
    director: 'Chan-wook Park',
    actors: 'Min-sik Choi, Ji-tae Yu, Hye-jeong Kang, Dae-han Ji',
    plot: 'After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_SX300.jpg',
  },
  {
    id: 71,
    title: 'American History X',
    year: '1998',
    runtime: '119',
    genres: ['Crime', 'Drama'],
    director: 'Tony Kaye',
    actors: "Edward Norton, Edward Furlong, Beverly D'Angelo, Jennifer Lien",
    plot: 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0MTM4MTQtNzY5MC00NzY3LWI1ZTgtYzcxMjkyMzU4MDZiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg',
  },
  {
    id: 81,
    title: 'WALL·E',
    year: '2008',
    runtime: '98',
    genres: ['Animation', 'Adventure', 'Family'],
    director: 'Andrew Stanton',
    actors: 'Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard',
    plot: 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTczOTA3MzY2N15BMl5BanBnXkFtZTcwOTYwNjE2MQ@@._V1_SX300.jpg',
  },
  {
    id: 86,
    title: 'The Grand Budapest Hotel',
    year: '2014',
    runtime: '99',
    genres: ['Adventure', 'Comedy', 'Crime'],
    director: 'Wes Anderson',
    actors: 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody',
    plot: 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg',
  },
  {
    id: 90,
    title: 'V for Vendetta',
    year: '2005',
    runtime: '132',
    genres: ['Action', 'Drama', 'Thriller'],
    director: 'James McTeigue',
    actors: 'Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry',
    plot: 'In a future British tyranny, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow it with the help of a young woman.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SX300.jpg',
  },
  {
    id: 110,
    title: 'Spirited Away',
    year: '2001',
    runtime: '125',
    genres: ['Animation', 'Adventure', 'Family'],
    director: 'Hayao Miyazaki',
    actors: 'Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naitô',
    plot: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYxMDcyMzIzNl5BMl5BanBnXkFtZTYwNDg2MDU3._V1_SX300.jpg',
  },
  {
    id: 114,
    title: '12 Angry Men',
    year: '1957',
    runtime: '96',
    genres: ['Crime', 'Drama'],
    director: 'Sidney Lumet',
    actors: 'Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall',
    plot: 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SX300.jpg',
  },
  {
    id: 115,
    title: 'The Imitation Game',
    year: '2014',
    runtime: '114',
    genres: ['Biography', 'Drama', 'Thriller'],
    director: 'Morten Tyldum',
    actors:
      'Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear',
    plot: 'During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1_SX300.jpg',
  },
  {
    id: 116,
    title: 'Interstellar',
    year: '2014',
    runtime: '169',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    director: 'Christopher Nolan',
    actors: 'Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow',
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg',
  },
  {
    id: 120,
    title: 'Sin City',
    year: '2005',
    runtime: '124',
    genres: ['Crime', 'Thriller'],
    director: 'Frank Miller, Robert Rodriguez, Quentin Tarantino',
    actors: 'Jessica Alba, Devon Aoki, Alexis Bledel, Powers Boothe',
    plot: 'A film that explores the dark and miserable town, Basin City, and tells the story of three different people, all caught up in violent corruption.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BODZmYjMwNzEtNzVhNC00ZTRmLTk2M2UtNzE1MTQ2ZDAxNjc2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
  },
  {
    id: 134,
    title: 'Ex Machina',
    year: '2015',
    runtime: '108',
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    director: 'Alex Garland',
    actors: 'Domhnall Gleeson, Corey Johnson, Oscar Isaac, Alicia Vikander',
    plot: 'A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a breath-taking humanoid A.I.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_SX300.jpg',
  },
  {
    id: 139,
    title: 'Whiplash',
    year: '2014',
    runtime: '107',
    genres: ['Drama', 'Music'],
    director: 'Damien Chazelle',
    actors: 'Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist',
    plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTU4OTQ3MDUyMV5BMl5BanBnXkFtZTgwOTA2MjU0MjE@._V1_SX300.jpg',
  },
  {
    id: 141,
    title: 'Hotel Rwanda',
    year: '2004',
    runtime: '121',
    genres: ['Drama', 'History', 'War'],
    director: 'Terry George',
    actors: 'Xolani Mali, Don Cheadle, Desmond Dube, Hakeem Kae-Kazim',
    plot: 'Paul Rusesabagina was a hotel manager who housed over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTI2MzQyNTc1M15BMl5BanBnXkFtZTYwMjExNjc3._V1_SX300.jpg',
  },
  {
    id: 142,
    title: 'The Martian',
    year: '2015',
    runtime: '144',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    director: 'Ridley Scott',
    actors: 'Matt Damon, Jessica Chastain, Kristen Wiig, Jeff Daniels',
    plot: 'An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.',
    posterUrl:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg',
  },
];
